[2025-09-27 17:42:01,127: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:42:01,128: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:42:53,883: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:42:53,894: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:49:04,580: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:49:04,582: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:51:25,287: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:51:25,289: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:51:35,495: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:51:35,497: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:51:35,499: INFO: common]: Directory created at: artifacts
[2025-09-27 17:52:17,625: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:52:17,628: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:52:17,630: INFO: common]: Directory created at: artifacts
[2025-09-27 17:53:53,298: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:53:53,301: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:53:53,302: INFO: common]: Directory created at: artifacts
[2025-09-27 17:55:31,643: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:55:31,645: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:55:31,646: INFO: common]: Directory created at: artifacts
[2025-09-27 17:57:22,258: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:57:22,260: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:57:22,261: INFO: common]: Directory created at: artifacts
[2025-09-27 17:58:13,194: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:58:13,196: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:58:13,197: INFO: common]: Directory created at: artifacts
[2025-09-27 17:58:45,292: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 17:58:45,295: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 17:58:45,297: INFO: common]: Directory created at: artifacts
[2025-09-27 17:58:45,298: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-27 18:02:10,953: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 18:02:10,955: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 18:02:10,956: INFO: common]: Directory created at: artifacts
[2025-09-27 18:02:10,958: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-27 18:05:16,751: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 18:05:16,753: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 18:05:16,754: INFO: common]: Directory created at: artifacts
[2025-09-27 18:05:16,754: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-27 18:05:20,454: INFO: 717126125]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-27 18:05:20,455: INFO: 717126125]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-27 21:28:55,793: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:28:55,805: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:28:55,806: INFO: common]: Directory created at: artifacts
[2025-09-27 21:29:16,734: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:29:16,737: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:29:16,738: INFO: common]: Directory created at: artifacts
[2025-09-27 21:34:10,457: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:34:10,459: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:34:10,460: INFO: common]: Directory created at: artifacts
[2025-09-27 21:37:07,223: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:37:07,226: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:37:07,227: INFO: common]: Directory created at: artifacts
[2025-09-27 21:37:07,228: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-27 21:37:42,116: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:37:42,118: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:37:42,120: INFO: common]: Directory created at: artifacts
[2025-09-27 21:37:42,120: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-27 21:38:19,655: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:38:19,658: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:38:19,659: INFO: common]: Directory created at: artifacts
[2025-09-27 21:38:19,660: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-27 21:38:33,411: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:38:33,414: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:38:33,415: INFO: common]: Directory created at: artifacts
[2025-09-27 21:38:33,415: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-27 21:38:33,767: INFO: 1567097251]: Model: ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (4): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (5): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=512, out_features=7, bias=True)
) - Parameters: 21288263
[2025-09-27 21:48:55,455: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-27 21:48:55,456: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:48:55,458: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:48:55,458: INFO: common]: Directory created at: artifacts
[2025-09-27 21:48:55,458: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-27 21:49:02,381: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-27 21:49:02,382: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-27 21:49:02,382: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-27 21:49:02,382: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-27 21:49:02,383: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:49:02,385: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:49:02,385: INFO: common]: Directory created at: artifacts
[2025-09-27 21:49:02,386: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-27 21:49:02,386: ERROR: main]: >>>>>> stage Prepare Base Model stage failed <<<<<<
[2025-09-27 21:49:02,386: ERROR: main]: name 'os' is not defined
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 20, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\config\configuration.py", line 36, in get_prepare_base_model_config
    base_model_path=Path(os.path.join(config.base_model_path)),
NameError: name 'os' is not defined
[2025-09-27 21:49:51,543: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-27 21:49:51,544: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:49:51,546: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:49:51,547: INFO: common]: Directory created at: artifacts
[2025-09-27 21:49:51,547: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-27 21:49:57,160: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-27 21:49:57,161: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-27 21:49:57,161: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-27 21:49:57,162: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-27 21:49:57,167: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 21:49:57,169: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 21:49:57,169: INFO: common]: Directory created at: artifacts
[2025-09-27 21:49:57,169: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-27 21:49:57,436: INFO: prepare_base_model]: Model: ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (4): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (5): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=512, out_features=7, bias=True)
) - Parameters: 21288263
[2025-09-27 21:49:57,507: INFO: main]: >>>>>> stage Prepare Base Model stage completed <<<<<<

x==========x
[2025-09-28 09:43:34,819: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:43:34,831: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:43:34,833: INFO: common]: Directory created at: artifacts
[2025-09-28 09:43:34,834: ERROR: 4016484038]: "'ConfigBox' object has no attribute 'trained_model'"
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'trained_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'trained_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'trained_model'. Did you mean: 'trained_model_path'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'trained_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'trained_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'trained_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'trained_model'. Did you mean: 'trained_model_path'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\2991876576.py", line 14, in get_training_config
    trained_model_path = os.path.join(training_config.trained_model)
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'trained_model'". Did you mean: 'trained_model_path'?
[2025-09-28 09:44:02,940: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:44:02,942: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:44:02,943: INFO: common]: Directory created at: artifacts
[2025-09-28 09:44:02,943: ERROR: 4016484038]: "'ConfigBox' object has no attribute 'trained_model'"
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'trained_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'trained_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'trained_model'. Did you mean: 'trained_model_path'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'trained_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'trained_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'trained_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'trained_model'. Did you mean: 'trained_model_path'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\2991876576.py", line 14, in get_training_config
    trained_model_path = os.path.join(training_config.trained_model)
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'trained_model'". Did you mean: 'trained_model_path'?
[2025-09-28 09:44:12,855: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:44:12,857: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:44:12,858: INFO: common]: Directory created at: artifacts
[2025-09-28 09:44:12,858: ERROR: 4016484038]: "'ConfigBox' object has no attribute 'updated_base_model'"
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'updated_base_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'updated_base_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\362330020.py", line 15, in get_training_config
    updated_base_model_path = os.path.join(training_config.updated_base_model)
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model'"
[2025-09-28 09:44:38,688: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:44:38,691: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:44:38,692: INFO: common]: Directory created at: artifacts
[2025-09-28 09:44:38,692: ERROR: 4016484038]: "'ConfigBox' object has no attribute 'updated_base_model_path'"
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\1590291379.py", line 15, in get_training_config
    updated_base_model_path = os.path.join(training_config.updated_base_model_path)
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"
[2025-09-28 09:45:59,786: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:45:59,788: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:45:59,789: INFO: common]: Directory created at: artifacts
[2025-09-28 09:45:59,789: ERROR: 4016484038]: 'ConfigurationManager' object has no attribute 'training_config'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\1020190894.py", line 17, in get_training_config
    dataset_path = os.path.join(self.training_config.dataset_path)
AttributeError: 'ConfigurationManager' object has no attribute 'training_config'. Did you mean: 'get_training_config'?
[2025-09-28 09:47:28,733: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:47:28,735: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:47:28,736: INFO: common]: Directory created at: artifacts
[2025-09-28 09:47:28,736: ERROR: 4016484038]: 'ConfigurationManager' object has no attribute 'training_config'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\1020190894.py", line 17, in get_training_config
    dataset_path = os.path.join(self.training_config.dataset_path)
AttributeError: 'ConfigurationManager' object has no attribute 'training_config'. Did you mean: 'get_training_config'?
[2025-09-28 09:48:43,387: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:48:43,388: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:48:43,389: INFO: common]: Directory created at: artifacts
[2025-09-28 09:48:43,390: ERROR: 4016484038]: Argument path_to_directories of type <class 'pathlib.WindowsPath'> to <function create_directories at 0x0000013EDAED9CF0> does not match annotation type <class 'list'>
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\1109426850.py", line 19, in get_training_config
    create_directories(Path(training_config.root_dir))
  File "c:\Users\namnh\miniconda3\envs\FER\lib\site-packages\ensure\main.py", line 833, in __call__
    raise EnsureError(msg.format(arg=arg, f=self.f, t=templ, valt=type(value)))
ensure.main.EnsureError: Argument path_to_directories of type <class 'pathlib.WindowsPath'> to <function create_directories at 0x0000013EDAED9CF0> does not match annotation type <class 'list'>
[2025-09-28 09:49:35,237: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:49:35,239: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:49:35,240: INFO: common]: Directory created at: artifacts
[2025-09-28 09:49:35,241: INFO: common]: Directory created at: artifacts\training
[2025-09-28 09:49:35,241: ERROR: 4016484038]: "'ConfigBox' object has no attribute 'num_classes'"
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'NUM_CLASSES'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'NUM_CLASSES'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'NUM_CLASSES'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'NUM_CLASSES'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'num_classes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'num_classes'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'num_classes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\905312459.py", line 26, in get_training_config
    params_num_classes = params.NUM_CLASSES
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'num_classes'"
[2025-09-28 09:50:42,444: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:50:42,455: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:50:42,456: INFO: common]: Directory created at: artifacts
[2025-09-28 09:50:42,457: INFO: common]: Directory created at: artifacts\training
[2025-09-28 09:50:42,458: ERROR: 4016484038]: TrainingConfig.__init__() got an unexpected keyword argument 'dataset_path'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\4016484038.py", line 3, in <module>
    training_config = config.get_training_config()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_9468\905312459.py", line 29, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() got an unexpected keyword argument 'dataset_path'
[2025-09-28 09:53:11,226: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:53:11,229: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:53:11,231: INFO: common]: Directory created at: artifacts
[2025-09-28 09:53:11,232: INFO: common]: Directory created at: artifacts\training
[2025-09-28 09:53:11,313: ERROR: 4016484038]: [Errno 2] No such file or directory: 'artifacts\\data'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\1488135359.py", line 18, in train
    self.extract_dataset()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\1488135359.py", line 9, in extract_dataset
    with ZipFile(self.config.dataset_path, 'r') as zip_ref:
  File "c:\Users\namnh\miniconda3\envs\FER\lib\zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data'
[2025-09-28 09:55:27,815: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:55:27,817: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:55:27,818: INFO: common]: Directory created at: artifacts
[2025-09-28 09:55:27,819: INFO: common]: Directory created at: artifacts\training
[2025-09-28 09:55:27,896: ERROR: 4016484038]: [Errno 13] Permission denied: 'artifacts\\data'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\143940723.py", line 19, in train
    self.extract_dataset()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\143940723.py", line 10, in extract_dataset
    with ZipFile(self.config.dataset_path, 'r') as zip_ref:
  File "c:\Users\namnh\miniconda3\envs\FER\lib\zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'artifacts\\data'
[2025-09-28 09:57:55,738: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:57:55,741: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:57:55,741: INFO: common]: Directory created at: artifacts
[2025-09-28 09:57:55,743: INFO: common]: Directory created at: artifacts\training
[2025-09-28 09:57:55,810: ERROR: 4016484038]: [Errno 13] Permission denied: 'artifacts\\data'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\3037046892.py", line 19, in train
    self.extract_dataset()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_19772\3037046892.py", line 10, in extract_dataset
    with ZipFile(self.config.dataset_path, 'r') as zip_ref:
  File "c:\Users\namnh\miniconda3\envs\FER\lib\zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'artifacts\\data'
[2025-09-28 09:58:58,626: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 09:58:58,629: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 09:58:58,633: INFO: common]: Directory created at: artifacts
[2025-09-28 09:58:58,635: INFO: common]: Directory created at: artifacts\training
[2025-09-28 09:58:58,721: ERROR: 4016484038]: [Errno 13] Permission denied: 'artifacts\\data'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\3037046892.py", line 19, in train
    self.extract_dataset()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\3037046892.py", line 10, in extract_dataset
    with ZipFile(self.config.dataset_path, 'r') as zip_ref:
  File "c:\Users\namnh\miniconda3\envs\FER\lib\zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'artifacts\\data'
[2025-09-28 10:00:28,887: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:00:28,889: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:00:28,890: INFO: common]: Directory created at: artifacts
[2025-09-28 10:00:28,891: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:00:28,958: ERROR: 4016484038]: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\data'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\983365999.py", line 19, in train
    self.extract_dataset()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\983365999.py", line 9, in extract_dataset
    with ZipFile(self.config.training_data_path, 'r') as zip_ref:
  File "c:\Users\namnh\miniconda3\envs\FER\lib\zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\data'
[2025-09-28 10:02:10,318: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:02:10,320: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:02:10,321: INFO: common]: Directory created at: artifacts
[2025-09-28 10:02:10,322: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:02:10,397: ERROR: 4016484038]: [Errno 13] Permission denied: 'artifacts\\data_ingestion'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\983365999.py", line 19, in train
    self.extract_dataset()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\983365999.py", line 9, in extract_dataset
    with ZipFile(self.config.training_data_path, 'r') as zip_ref:
  File "c:\Users\namnh\miniconda3\envs\FER\lib\zipfile.py", line 1254, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion'
[2025-09-28 10:02:33,712: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:02:33,713: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:02:33,714: INFO: common]: Directory created at: artifacts
[2025-09-28 10:02:33,715: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:02:46,426: ERROR: 4016484038]: 'collections.OrderedDict' object has no attribute 'to'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\983365999.py", line 25, in train
    self.model = self.model.to(device)
AttributeError: 'collections.OrderedDict' object has no attribute 'to'
[2025-09-28 10:03:53,345: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:03:53,347: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:03:53,348: INFO: common]: Directory created at: artifacts
[2025-09-28 10:03:53,349: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:04:03,614: ERROR: 4016484038]: 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\3999930852.py", line 25, in train
    self.model = self.get_model().to(device)
AttributeError: 'NoneType' object has no attribute 'to'
[2025-09-28 10:05:10,772: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:05:10,774: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:05:10,775: INFO: common]: Directory created at: artifacts
[2025-09-28 10:05:10,776: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:05:20,512: ERROR: 4016484038]: 'collections.OrderedDict' object has no attribute 'to'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\431402426.py", line 27, in train
    self.model = self.model.to(device)
AttributeError: 'collections.OrderedDict' object has no attribute 'to'
[2025-09-28 10:07:04,891: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:07:04,893: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:07:04,894: INFO: common]: Directory created at: artifacts
[2025-09-28 10:07:04,895: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:07:05,311: ERROR: 4016484038]: Error(s) in loading state_dict for ResNet:
	size mismatch for fc.weight: copying a param with shape torch.Size([7, 512]) from checkpoint, the shape in current model is torch.Size([1000, 512]).
	size mismatch for fc.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([1000]).
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\4016484038.py", line 5, in <module>
    training.get_model()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_16100\366108171.py", line 7, in get_model
    self.model = self.model.load_state_dict(torch.load(self.config.updated_base_model_path))
  File "c:\Users\namnh\miniconda3\envs\FER\lib\site-packages\torch\nn\modules\module.py", line 2624, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for fc.weight: copying a param with shape torch.Size([7, 512]) from checkpoint, the shape in current model is torch.Size([1000, 512]).
	size mismatch for fc.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([1000]).
[2025-09-28 10:15:14,987: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:15:14,990: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:15:14,992: INFO: common]: Directory created at: artifacts
[2025-09-28 10:15:14,993: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:16:37,187: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 10:16:37,198: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 10:16:37,199: INFO: common]: Directory created at: artifacts
[2025-09-28 10:16:37,200: INFO: common]: Directory created at: artifacts\training
[2025-09-28 10:26:43,975: INFO: 3183951286]: Model saved at artifacts\training\model.h5
[2025-09-28 10:26:43,987: INFO: 4016484038]: Training completed successfully.
[2025-09-28 15:59:39,719: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-28 15:59:39,722: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 15:59:39,725: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 15:59:39,726: INFO: common]: Directory created at: artifacts
[2025-09-28 15:59:39,726: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-28 15:59:44,324: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-28 15:59:44,325: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-28 15:59:44,325: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-28 15:59:44,325: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-28 15:59:44,327: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 15:59:44,328: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 15:59:44,328: INFO: common]: Directory created at: artifacts
[2025-09-28 15:59:44,329: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-28 15:59:44,329: ERROR: main]: >>>>>> stage Prepare Base Model stage failed <<<<<<
[2025-09-28 15:59:44,329: ERROR: main]: PrepareBaseModel.get_model() got an unexpected keyword argument 'pretrained'
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 21, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 26, in update_base_model
    model = self.get_model(pretrained=True)
TypeError: PrepareBaseModel.get_model() got an unexpected keyword argument 'pretrained'
[2025-09-28 15:59:44,329: INFO: main]: >>>>>> stage Training stage started <<<<<<
[2025-09-28 15:59:44,331: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 15:59:44,332: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 15:59:44,333: INFO: common]: Directory created at: artifacts
[2025-09-28 15:59:44,333: INFO: common]: Directory created at: artifacts\training
[2025-09-28 16:09:55,091: INFO: training_model]: Model saved at artifacts\training\model.pth
[2025-09-28 16:09:55,112: INFO: main]: >>>>>> stage Training stage completed <<<<<<

x==========x
[2025-09-28 16:58:04,416: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 16:58:04,421: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 16:58:04,422: INFO: common]: Directory created at: artifacts
[2025-09-28 16:58:04,423: INFO: common]: Directory created at: artifacts\training
[2025-09-28 16:58:16,891: ERROR: 4016484038]: unsupported operand type(s) for +: 'WindowsPath' and 'str'
Traceback (most recent call last):
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_23844\4016484038.py", line 6, in <module>
    training.train()
  File "C:\Users\namnh\AppData\Local\Temp\ipykernel_23844\288087573.py", line 39, in train
    train_data = torchvision.datasets.ImageFolder(root=self.config.dataset_path + "/FER2013/train", transform=train_transforms)
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
[2025-09-28 17:01:49,707: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:01:49,709: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:01:49,710: INFO: common]: Directory created at: artifacts
[2025-09-28 17:01:49,711: INFO: common]: Directory created at: artifacts\training
[2025-09-28 17:09:43,066: INFO: 1622891604]: Model saved at artifacts\training\model.pth
[2025-09-28 17:09:43,080: INFO: 4016484038]: Training completed successfully.
[2025-09-28 17:33:30,711: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:33:30,715: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:33:30,716: INFO: common]: Directory created at: artifacts
[2025-09-28 17:34:27,065: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:34:27,068: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:34:27,069: INFO: common]: Directory created at: artifacts
[2025-09-28 17:35:00,680: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:35:00,683: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:35:00,684: INFO: common]: Directory created at: artifacts
[2025-09-28 17:35:37,251: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:35:37,253: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:35:37,255: INFO: common]: Directory created at: artifacts
[2025-09-28 17:36:47,191: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:36:47,193: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:36:47,194: INFO: common]: Directory created at: artifacts
[2025-09-28 17:36:56,297: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:36:56,299: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:36:56,300: INFO: common]: Directory created at: artifacts
[2025-09-28 17:37:42,114: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:37:42,116: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:37:42,117: INFO: common]: Directory created at: artifacts
[2025-09-28 17:37:59,846: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:37:59,848: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:37:59,850: INFO: common]: Directory created at: artifacts
[2025-09-28 17:38:33,164: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:38:33,166: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:38:33,167: INFO: common]: Directory created at: artifacts
[2025-09-28 17:39:46,391: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:39:46,393: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:39:46,394: INFO: common]: Directory created at: artifacts
[2025-09-28 17:42:02,658: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:42:02,661: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:42:02,662: INFO: common]: Directory created at: artifacts
[2025-09-28 17:42:31,182: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:42:31,184: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:42:31,185: INFO: common]: Directory created at: artifacts
[2025-09-28 17:43:26,014: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:43:26,016: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:43:26,018: INFO: common]: Directory created at: artifacts
[2025-09-28 17:43:48,907: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:43:48,909: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:43:48,911: INFO: common]: Directory created at: artifacts
[2025-09-28 17:46:43,733: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:46:43,735: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:46:43,736: INFO: common]: Directory created at: artifacts
[2025-09-28 17:46:52,386: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:46:52,388: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:46:52,389: INFO: common]: Directory created at: artifacts
[2025-09-28 17:48:37,821: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:48:37,823: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:48:37,824: INFO: common]: Directory created at: artifacts
[2025-09-28 17:53:15,748: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:53:15,750: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:53:15,752: INFO: common]: Directory created at: artifacts
[2025-09-28 17:53:30,941: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:53:30,944: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:53:30,946: INFO: common]: Directory created at: artifacts
[2025-09-28 17:53:56,985: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:53:56,989: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:53:56,990: INFO: common]: Directory created at: artifacts
[2025-09-28 17:54:05,862: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:54:05,863: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:54:05,864: INFO: common]: Directory created at: artifacts
[2025-09-28 17:54:26,076: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:54:26,079: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:54:26,080: INFO: common]: Directory created at: artifacts
[2025-09-28 17:55:14,936: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:55:14,938: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:55:14,939: INFO: common]: Directory created at: artifacts
[2025-09-28 17:55:58,404: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:55:58,406: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:55:58,407: INFO: common]: Directory created at: artifacts
[2025-09-28 17:56:42,621: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:56:42,623: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:56:42,624: INFO: common]: Directory created at: artifacts
[2025-09-28 17:56:57,058: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:56:57,060: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:56:57,061: INFO: common]: Directory created at: artifacts
[2025-09-28 17:57:14,536: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:57:14,538: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:57:14,539: INFO: common]: Directory created at: artifacts
[2025-09-28 17:57:30,865: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:57:30,867: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:57:30,868: INFO: common]: Directory created at: artifacts
[2025-09-28 17:58:06,972: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:58:06,974: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:58:06,975: INFO: common]: Directory created at: artifacts
[2025-09-28 17:58:45,100: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:58:45,102: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:58:45,103: INFO: common]: Directory created at: artifacts
[2025-09-28 17:59:21,569: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:59:21,571: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:59:21,572: INFO: common]: Directory created at: artifacts
[2025-09-28 18:02:19,508: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:02:19,510: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:02:19,510: INFO: common]: Directory created at: artifacts
[2025-09-28 18:03:03,678: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:03:03,681: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:03:03,682: INFO: common]: Directory created at: artifacts
[2025-09-28 18:04:31,332: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:04:31,335: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:04:31,336: INFO: common]: Directory created at: artifacts
[2025-09-28 18:04:31,338: INFO: common]: Directory created at: artifacts\training
[2025-09-28 18:12:32,516: INFO: 2594059182]: Model saved at artifacts\training\model.pth
[2025-09-28 18:12:32,528: INFO: 4016484038]: Training completed successfully.
[2025-09-28 18:25:56,648: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:25:56,650: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:25:56,651: INFO: common]: Directory created at: artifacts
[2025-09-28 18:26:18,259: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:26:18,261: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:26:18,262: INFO: common]: Directory created at: artifacts
[2025-09-28 18:33:41,070: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:33:41,073: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:33:41,074: INFO: common]: Directory created at: artifacts
[2025-09-28 18:40:44,650: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:40:44,652: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:40:44,653: INFO: common]: Directory created at: artifacts
[2025-09-28 18:44:28,051: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:44:28,053: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:44:28,055: INFO: common]: Directory created at: artifacts
[2025-09-28 18:46:00,807: INFO: common]: JSON file saved at: scores.json
[2025-09-28 18:48:25,842: INFO: _client]: HTTP Request: POST https://dagshub.com/login/oauth/middleman "HTTP/1.1 200 OK"
[2025-09-28 18:48:26,220: INFO: _client]: HTTP Request: POST https://dagshub.com/login/oauth/access_token "HTTP/1.1 200 OK"
[2025-09-28 18:48:26,638: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-09-28 18:48:26,645: INFO: helpers]: Accessing as nhut-nam
[2025-09-28 18:48:27,131: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/repos/nhut-nam/FaceEmotionRecognitionSystemTest "HTTP/1.1 200 OK"
[2025-09-28 18:48:27,562: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-09-28 18:48:27,566: INFO: helpers]: Initialized MLflow to track repo "nhut-nam/FaceEmotionRecognitionSystemTest"
[2025-09-28 18:48:27,568: INFO: helpers]: Repository nhut-nam/FaceEmotionRecognitionSystemTest initialized!
[2025-09-28 18:48:54,888: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:48:54,890: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:48:54,891: INFO: common]: Directory created at: artifacts
[2025-09-28 18:50:27,841: INFO: common]: JSON file saved at: scores.json
[2025-09-28 18:51:14,565: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 18:51:14,566: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 18:51:14,567: INFO: common]: Directory created at: artifacts
[2025-09-28 18:52:46,289: INFO: common]: JSON file saved at: scores.json
[2025-09-28 19:02:01,220: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-28 19:02:01,224: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:02:01,233: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:02:01,233: INFO: common]: Directory created at: artifacts
[2025-09-28 19:02:01,234: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-28 19:02:05,122: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-28 19:02:05,123: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-28 19:02:05,124: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-28 19:02:05,124: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-28 19:02:05,126: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:02:05,127: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:02:05,128: INFO: common]: Directory created at: artifacts
[2025-09-28 19:02:05,128: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-28 19:02:05,128: ERROR: main]: >>>>>> stage Prepare Base Model stage failed <<<<<<
[2025-09-28 19:02:05,128: ERROR: main]: 'PrepareBaseModelConfig' object has no attribute 'model_name'
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 22, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 26, in update_base_model
    model = self.get_model(pretrained=True)
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 16, in get_model
    if self.config.model_name == "resnet34":
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'model_name'
[2025-09-28 19:02:05,128: INFO: main]: >>>>>> stage Training stage started <<<<<<
[2025-09-28 19:02:05,130: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:02:05,131: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:02:05,131: INFO: common]: Directory created at: artifacts
[2025-09-28 19:02:05,132: INFO: common]: Directory created at: artifacts\training
[2025-09-28 19:10:04,849: INFO: training_model]: Model saved at artifacts\training\model.pth
[2025-09-28 19:10:04,866: INFO: main]: >>>>>> stage Training stage completed <<<<<<

x==========x
[2025-09-28 19:10:04,866: INFO: main]: >>>>>> stage Model Evaluation stage started <<<<<<
[2025-09-28 19:10:04,869: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:10:04,871: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:10:04,872: INFO: common]: Directory created at: artifacts
[2025-09-28 19:10:05,175: ERROR: main]: >>>>>> stage Model Evaluation stage failed <<<<<<
[2025-09-28 19:10:05,176: ERROR: main]: Expected state_dict to be dict-like, got <class 'torchvision.models.resnet.ResNet'>.
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 44, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_04_model_evalution_with_mlflow.py", line 15, in main
    model_eval.evaluate()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\model_evalution_with_mlflow.py", line 19, in evaluate
    self.model = self.load_model(model_path=self.config.path_of_model, params=self.config.all_params)
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\model_evalution_with_mlflow.py", line 79, in load_model
    model.load_state_dict(checkpoint)
  File "C:\Users\namnh\miniconda3\envs\FER\lib\site-packages\torch\nn\modules\module.py", line 2556, in load_state_dict
    raise TypeError(
TypeError: Expected state_dict to be dict-like, got <class 'torchvision.models.resnet.ResNet'>.
[2025-09-28 19:12:09,939: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-28 19:12:09,942: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:12:09,943: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:12:09,944: INFO: common]: Directory created at: artifacts
[2025-09-28 19:12:09,944: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-28 19:12:13,400: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-28 19:12:13,400: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-28 19:12:13,401: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-28 19:12:13,401: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-28 19:12:13,404: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:12:13,408: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:12:13,409: INFO: common]: Directory created at: artifacts
[2025-09-28 19:12:13,409: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-28 19:12:13,410: ERROR: main]: >>>>>> stage Prepare Base Model stage failed <<<<<<
[2025-09-28 19:12:13,410: ERROR: main]: 'PrepareBaseModelConfig' object has no attribute 'model_name'
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 22, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 26, in update_base_model
    model = self.get_model(pretrained=True)
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 16, in get_model
    if self.config.model_name == "resnet34":
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'model_name'
[2025-09-28 19:12:13,410: INFO: main]: >>>>>> stage Training stage started <<<<<<
[2025-09-28 19:12:13,413: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:12:13,417: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:12:13,418: INFO: common]: Directory created at: artifacts
[2025-09-28 19:12:13,418: INFO: common]: Directory created at: artifacts\training
[2025-09-28 19:19:58,793: INFO: training_model]: Model saved at artifacts\training\model.pth
[2025-09-28 19:19:58,812: INFO: main]: >>>>>> stage Training stage completed <<<<<<

x==========x
[2025-09-28 19:19:58,813: INFO: main]: >>>>>> stage Model Evaluation stage started <<<<<<
[2025-09-28 19:19:58,827: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:19:58,837: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:19:58,838: INFO: common]: Directory created at: artifacts
[2025-09-28 19:24:29,992: INFO: common]: JSON file saved at: scores.json
[2025-09-28 19:24:39,493: INFO: main]: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x
[2025-09-28 19:28:49,082: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-28 19:28:49,084: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:28:49,093: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:28:49,094: INFO: common]: Directory created at: artifacts
[2025-09-28 19:28:49,094: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-28 19:28:52,919: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-28 19:28:52,920: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-28 19:28:52,920: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-28 19:28:52,920: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-28 19:28:52,925: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:28:52,926: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:28:52,926: INFO: common]: Directory created at: artifacts
[2025-09-28 19:28:52,926: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-28 19:28:52,927: ERROR: main]: >>>>>> stage Prepare Base Model stage failed <<<<<<
[2025-09-28 19:28:52,927: ERROR: main]: 'PrepareBaseModelConfig' object has no attribute 'model_name'
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 22, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 26, in update_base_model
    model = self.get_model(pretrained=True)
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 16, in get_model
    if self.config.model_name == "resnet34":
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'model_name'
[2025-09-28 19:28:52,928: INFO: main]: >>>>>> stage Training stage started <<<<<<
[2025-09-28 19:28:52,932: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:28:52,935: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:28:52,935: INFO: common]: Directory created at: artifacts
[2025-09-28 19:28:52,936: INFO: common]: Directory created at: artifacts\training
[2025-09-28 19:41:00,837: INFO: training_model]: Model saved at artifacts\training\model.pth
[2025-09-28 19:41:00,857: INFO: main]: >>>>>> stage Training stage completed <<<<<<

x==========x
[2025-09-28 19:41:00,857: INFO: main]: >>>>>> stage Model Evaluation stage started <<<<<<
[2025-09-28 19:41:00,859: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:41:00,861: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:41:00,861: INFO: common]: Directory created at: artifacts
[2025-09-28 19:43:34,865: INFO: common]: JSON file saved at: scores.json
[2025-09-28 19:43:44,537: INFO: main]: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x
[2025-09-28 19:46:50,442: INFO: main]: >>>>>> stage Data Ingestion stage started <<<<<<
[2025-09-28 19:46:50,446: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:46:50,447: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:46:50,447: INFO: common]: Directory created at: artifacts
[2025-09-28 19:46:50,448: INFO: common]: Directory created at: artifacts/data_ingestion
[2025-09-28 19:46:54,063: INFO: data_ingestion]: Downloaded file from :[https://drive.google.com/file/d/10cuSJ1L8N5CT5cmLvieyCf5TFtEz1lLy/view?usp=sharing] and saved at :[artifacts/data_ingestion/data.zip]
[2025-09-28 19:46:54,063: INFO: data_ingestion]: Zip file already extracted in dir :[artifacts/data_ingestion]
[2025-09-28 19:46:54,063: INFO: main]: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[2025-09-28 19:46:54,064: INFO: main]: >>>>>> stage Prepare Base Model stage started <<<<<<
[2025-09-28 19:46:54,066: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:46:54,068: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:46:54,069: INFO: common]: Directory created at: artifacts
[2025-09-28 19:46:54,069: INFO: common]: Directory created at: artifacts/prepare_base_model
[2025-09-28 19:46:54,069: ERROR: main]: >>>>>> stage Prepare Base Model stage failed <<<<<<
[2025-09-28 19:46:54,069: ERROR: main]: 'PrepareBaseModelConfig' object has no attribute 'model_name'
Traceback (most recent call last):
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\main.py", line 22, in <module>
    obj.main()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 26, in update_base_model
    model = self.get_model(pretrained=True)
  File "F:\ProjectAI\FaceEmotionRecognitionSystem\src\FacialExpressionRecognition\components\prepare_base_model.py", line 16, in get_model
    if self.config.model_name == "resnet34":
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'model_name'
[2025-09-28 19:46:54,070: INFO: main]: >>>>>> stage Training stage started <<<<<<
[2025-09-28 19:46:54,072: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:46:54,074: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:46:54,075: INFO: common]: Directory created at: artifacts
[2025-09-28 19:46:54,075: INFO: common]: Directory created at: artifacts\training
[2025-09-28 19:59:02,765: INFO: training_model]: Model saved at artifacts\training\model.pth
[2025-09-28 19:59:02,782: INFO: main]: >>>>>> stage Training stage completed <<<<<<

x==========x
[2025-09-28 19:59:04,278: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-09-28 19:59:04,285: INFO: helpers]: Accessing as nhut-nam
[2025-09-28 19:59:04,821: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/repos/nhut-nam/FaceEmotionRecognitionSystemTest "HTTP/1.1 200 OK"
[2025-09-28 19:59:05,231: INFO: _client]: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[2025-09-28 19:59:05,235: INFO: helpers]: Initialized MLflow to track repo "nhut-nam/FaceEmotionRecognitionSystemTest"
[2025-09-28 19:59:05,235: INFO: helpers]: Repository nhut-nam/FaceEmotionRecognitionSystemTest initialized!
[2025-09-28 19:59:05,235: INFO: main]: >>>>>> stage Model Evaluation stage started <<<<<<
[2025-09-28 19:59:05,237: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 19:59:05,238: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 19:59:05,239: INFO: common]: Directory created at: artifacts
[2025-09-28 20:01:39,121: INFO: common]: JSON file saved at: scores.json
[2025-09-28 20:02:53,895: INFO: main]: >>>>>> stage Model Evaluation stage completed <<<<<<

x==========x
